# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 02:22
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='博客标题')),
                ('category', models.CharField(max_length=50, verbose_name='博客标签')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='正文')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
