# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 13:14
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Aboutme')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='正文')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'Aboutme',
                'verbose_name_plural': 'Aboutme',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-add_time'], 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
    ]
