# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180323_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default=None, max_length=1000, verbose_name='博客摘要'),
        ),
    ]
